name: Build and Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build and Release nepalitokenizers
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Build Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build

      - name: Build Package
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}