name: Build nepalitokenizers package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade build

    - name: Build package
      run: python -m build

    - name: Upload package as artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          dist/*.tar.gz
          dist/*.whl